"""alter column is_locked of JsonObject

Revision ID: 44015f761a68
Revises: a6074f58eb13
Create Date: 2022-02-23 10:40:24.856123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44015f761a68"
down_revision = "a6074f58eb13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "json_object",
        "is_locked",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "json_object",
        "is_locked",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###
