"""Added boolean column is_membership_restricted to organization table.

Revision ID: 93451e9eda64
Revises: 029c7f524121
Create Date: 2021-03-24 09:03:06.862929

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "93451e9eda64"
down_revision = "029c7f524121"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column(
            "is_membership_restricted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.schema.DefaultClause("True"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "is_membership_restricted")
    # ### end Alembic commands ###
