"""added new event model

Revision ID: a6074f58eb13
Revises: 2c5b93302e8b
Create Date: 2022-02-23 10:35:28.929676

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a6074f58eb13"
down_revision = "2c5b93302e8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("initiator", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
