name: MOSP Docker build and push to ghcr.io

on:
  push:
    branches: [ 'master' ]
    tags: [ 'v*.*', 'v*.*.*', 'v*.*.*-*' ]
  pull_request:
    branches: [ 'master' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "PYTHON_VERSION=3.10-slim-buster"
            "NODE_VERSION=18-bullseye"
            "VERSION=${{ steps.meta.outputs.tags }}"
